export const portfolioItems = [
  {
    id: 1,
    title: "Bag",
    tags: ["Catalogue", "Static"],
    price: "₦25,000/image",
    image: "/assets/portfolio/bag.png",
  },
  {
    id: 2,
    title: "Beauty",
    tags: ["Dynamic", "Motion"],
    price: "₦65,000/image",
    image: "/assets/portfolio/shoe-2.png",
  },
  {
    id: 3,
    title: "Drinks",
    tags: ["Advertising", "Hero"],
    price: "₦44,000/image",
    image: "/assets/portfolio/drinks.png",
  },
  {
    id: 4,
    title: "Electronics",
    tags: ["Product", "Clean"],
    price: "₦35,000/image",
    image: "/assets/portfolio/clothing.png",
  },
  {
    id: 5,
    title: "Fashion",
    tags: ["Lifestyle", "Model"],
    price: "₦85,000/image",
    image: "/assets/portfolio/shoe-1.png",
  },
];

export const categories = [
  "ALL",
  "CLOTHING",
  "BAGS",
  "SHOES",
  "BEAUTY",
  "JEWELY",
  "DRINKS",
];

export const portfolios = [
  {
    id: 1,
    title: "Black and White Handbag",
    category: "BAGS",
    image: "/assets/portfolio/bags/1.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 2,
    title: "Diamond Necklace",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/1.jpg",
    details: "Model photography with focus on jewelry",
  },
  {
    id: 3,
    title: "Red Heels",
    category: "SHOES",
    image: "/assets/portfolio/shoes/1.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 4,
    title: "Designer Loafers",
    category: "SHOES",
    image: "/assets/portfolio/shoes/2.jpg",
    details: "Creative arrangement with custom props",
  },
  {
    id: 5,
    title: "Smartphone Product Shot",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/1.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 6,
    title: "Premium Smartphone",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/2.jpg",
    details: "Creative lighting technique for product highlight",
  },
  {
    id: 7,
    title: "Whiskey Bottle",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/1.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 8,
    title: "Designer Shirt",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/1.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 9,
    title: "Luxury Watch",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/2.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 10,
    title: "Luxury Watch",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/3.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 11,
    title: "Luxury Watch",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/4.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 12,
    title: "Smirnoff Vodka",

    category: "DRINKS",
    image: "/assets/portfolio/drinks/2.jpg",
    details: "Creative arrangement with custom props",
  },
  {
    id: 13,
    title: "Gucci Handbag",
    category: "BAGS",
    image: "/assets/portfolio/bags/2.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 14,
    title: "Black and White Handbag",
    category: "BAGS",
    image: "/assets/portfolio/bags/3.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 15,
    title: "Black and White Handbag",
    category: "BAGS",
    image: "/assets/portfolio/bags/4.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 16,
    title: "Black and White Handbag",
    category: "BAGS",
    image: "/assets/portfolio/bags/5.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 17,
    title: "Black and White Handbag",
    category: "BAGS",
    image: "/assets/portfolio/bags/6.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 19,
    title: "Gown",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/2.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 20,
    title: "Gown",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/3.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 21,
    title: "Gown",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/4.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 22,
    title: "Gown",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/5.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 23,
    title: "Gown",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/6.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 24,
    title: "heels",
    category: "SHOES",
    image: "/assets/portfolio/shoes/3.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 25,
    title: "heels",
    category: "SHOES",
    image: "/assets/portfolio/shoes/4.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 26,
    title: "heels",
    category: "SHOES",
    image: "/assets/portfolio/shoes/5.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 27,
    title: "heels",
    category: "SHOES",
    image: "/assets/portfolio/shoes/6.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 28,
    title: "heels",
    category: "SHOES",
    image: "/assets/portfolio/shoes/7.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 29,
    title: "spa",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/3.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 30,
    title: "spa",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/4.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 31,
    title: "spa",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/5.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 32,
    title: "spa",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/6.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 33,
    title: "spa",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/7.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 34,
    title: "spa",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/8.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 36,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/5.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 37,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/6.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 38,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/7.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 39,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/8.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 40,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/9.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 41,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/10.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 42,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/11.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 43,
    title: "rings",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/12.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 44,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/8.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 45,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/9.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 46,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/10.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 47,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/11.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 48,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/12.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 49,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/13.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 50,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/14.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 51,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/15.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 52,
    title: "flat shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/16.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 54,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/7.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 55,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/8.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 56,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/9.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 57,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/10.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 58,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/11.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 59,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/12.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 60,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/13.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 61,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/14.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 62,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/15.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 63,
    title: "gucci bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/16.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 64,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/3.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 65,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/4.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 66,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/5.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 67,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/6.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 68,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/7.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 69,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/8.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 70,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/9.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 71,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/10.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 72,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/11.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 73,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/12.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 74,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/13.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 75,
    title: "Whiskey",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/14.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 76,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/7.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 77,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/8.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 78,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/9.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 79,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/10.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 80,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/11.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 81,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/12.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 82,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/13.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 83,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/14.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 84,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/15.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 85,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/16.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 86,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/17.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 87,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/18.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 88,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/19.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 89,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/20.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 90,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/21.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 91,
    title: "Shorts",
    category: "CLOTHING",
    image: "/assets/portfolio/clothing/22.jpg",
    details: "Flatlay clothing photography with accessories",
  },
  {
    id: 92,
    title: "Bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/17.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 93,
    title: "Bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/18.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 94,
    title: "Bag",
    category: "BAGS",
    image: "/assets/portfolio/bags/19.jpg",
    details: "Studio product photography with clean background",
  },
  {
    id: 95,
    title: "Shoe",
    category: "SHOES",
    image: "/assets/portfolio/shoes/17.jpg",
    details: "Product photography with soft shadows",
  },
  {
    id: 97,
    title: "beauty",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/9.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 98,
    title: "beauty",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/10.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 99,
    title: "beauty",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/11.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 100,
    title: "beauty",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/12.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 101,
    title: "beauty",
    category: "BEAUTY",
    image: "/assets/portfolio/beauty/13.jpg",
    details: "Hand model showcasing device features",
  },
  {
    id: 102,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/13.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 103,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/14.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 104,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/15.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 105,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/16.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 106,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/17.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 107,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/18.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 108,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/19.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 109,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/20.jpg",
    details: "Macro photography showing intricate details",
  },

  {
    id: 110,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/21.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 111,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/22.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 112,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/23.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 113,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/24.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 114,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/25.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 115,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/26.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 116,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/27.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 117,
    title: "jewelry",
    category: "JEWELY",
    image: "/assets/portfolio/jewlery/28.jpg",
    details: "Macro photography showing intricate details",
  },
  {
    id: 118,
    title: "Drinks",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/15.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 119,
    title: "Drinks",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/16.jpg",
    details: "Premium product photography for alcohol",
  },
  {
    id: 120,
    title: "Drinks",
    category: "DRINKS",
    image: "/assets/portfolio/drinks/17.jpg",
    details: "Premium product photography for alcohol",
  },
];
